const assert=require('node:assert/strict');
const {createGame}=require('./harness.cjs');
const {box,nodes,storage,spoken,run,listeners}=createGame();
const plain=x=>JSON.parse(JSON.stringify(x));
assert.equal(nodes.previewButton.hidden,true);
const developer=createGame(undefined,false,{hostname:'localhost',search:'?dev=1'});
assert.equal(developer.nodes.previewButton.hidden,false);
assert.equal(typeof developer.nodes.previewButton.onclick,'function');
developer.run('startPreview();setPreviewPaused(true);seekPreview(.4)');
assert.equal(developer.run('previewPlaybackRate'),0);
assert.equal(developer.run('distance'),developer.run('TOTAL*.4'));
developer.run('setPreviewPaused(false)');
assert.equal(developer.run('previewPlaybackRate'),180);
assert.equal(run('rower.name'), 'Panu Musakka');assert.equal(run('selectedBoat.name'), 'Lonka');assert.equal(nodes.materialSelect.value,'mahogany');assert.equal(nodes.provisionPackSelect.value,'athlete');assert.equal(nodes.startButton.disabled,false);
run(`provisionPackSelect.value='athlete';rowerSelect.value=String(rowers.findIndex(r=>r.name==='Heikki Karjaluoto'));boatSelect.value=String(boats.findIndex(b=>b.name==='Lehto'));materialSelect.value='spruce';selectCrew();`);
assert.equal(run('rower.name'),'Heikki Karjaluoto');assert.equal(run('selectedBoat.name'),'Lehto');assert.equal(run('material'),'spruce');assert.equal(nodes.startButton.disabled,false);
assert.deepEqual(plain(run("initialInventory('fun')")),{gel:0,pickle:0,juice:0,saltwater:0,sportsdrink:0,candy:0,water:0,beer:12,cigarette:20,sausage:4,chips:0,donut:0,cola:0});
assert.deepEqual(plain(run("initialInventory('gourmet')")),{gel:0,pickle:0,juice:0,saltwater:0,sportsdrink:0,candy:20,water:0,beer:0,cigarette:0,sausage:0,chips:6,donut:8,cola:12});
run(`rowerChatter.reset();rowerChatter.arm(rower.name);rowerChatter.tick(60,{time:120,speed:10,active:true,wind:false,quality:.8,totalKm:58.3,freshness:100,energy:100,hydration:100,blisters:0,gutStress:20,digestionLoad:20,gutFluid:0,cramps:0});`);assert(run(`complaints.stomachEarly.includes(${JSON.stringify(spoken.at(-1).text)})`));
run(`rowerChatter.tick(60,{time:800,speed:10,active:true,wind:false,quality:.8,totalKm:58.3,freshness:100,energy:100,hydration:100,blisters:0,gutStress:60,digestionLoad:60,gutFluid:0,cramps:0});`);assert(run(`complaints.stomachSevere.includes(${JSON.stringify(spoken.at(-1).text)})`));
run(`rowerChatter.reset();rowerChatter.arm(rower.name);const originalRandom=Math.random;Math.random=()=>0;rowerChatter.intake('cigarette',120);Math.random=originalRandom;`);assert(run(`lines.smoke.includes(${JSON.stringify(spoken.at(-1).text)})`));
run(`selectedProvisionPack='fun';inventory=initialInventory('fun');running=true;alcoholLoad=nicotineLoad=0;consume('beer');const firstBeer=alcoholLoad;consume('beer');if(alcoholLoad<=firstBeer*2)throw Error('Alcohol stacking');strokePower=70;const cleanPower=effectiveStrokePower();consume('cigarette');const smokedPower=effectiveStrokePower();if(smokedPower>=cleanPower)throw Error('Nicotine power');const fluidBefore=fluidBalance,techniqueBefore=techniqueControl;strokeTimes=[performance.now()];updateBody(3600,section(),3600,true);if(fluidBalance>=fluidBefore||techniqueControl>=techniqueBefore)throw Error('Alcohol penalties');running=false;reset();`);
run(`selectedProvisionPack='gourmet';inventory=initialInventory('gourmet');running=true;bloodCarbs=10;gutStress=digestionLoad=0;consume('cola');if(bloodCarbs!==30)throw Error('Cola fast carbs');consume('chips');const firstDigestion=digestionLoad,firstStress=gutStress;consume('chips');if(digestionLoad<=firstDigestion*2||gutStress<=firstStress+foods.chips.stress)throw Error('Treat stacking');nicotineLoad=0;strokePower=70;if(effectiveStrokePower()>=70)throw Error('Digestion power');running=false;reset();`);
nodes.crewMenuButton.onclick();assert.equal(run('rower.name'),'Panu Musakka');assert.equal(run('selectedBoat.name'),'Lonka');assert.equal(run('material'),'mahogany');run(`provisionPackSelect.value='athlete';selectCrew();`);
run('start();');
assert.equal(spoken.at(-1).text,run('START_ANNOUNCEMENT'));
run(`raceElapsed=12600;distance=32000;speed=9.7;quality=.88;carbs=190;gutCarbs=16;fluidBalance=-.8;gutFluid=.2;sodiumBalance=-200;gutSodium=40;gutStress=12;wPrime=61;freshness=58;hydration=72;energy=42;blisters=23;cramps=17;inventory.gel=3;inventory.sportsdrink=12;saveRace();`);
const saved=JSON.parse(storage.get('suursoutu-race-v1'));
box.document.hidden=true;listeners.visibilitychange();run('update(3600,99999999)');assert.equal(run('raceElapsed'),12600);assert.equal(run('distance'),32000);box.document.hidden=false;
// Fresh VM: browser storage persists while all game state is reconstructed.
const fresh=createGame();fresh.storage.set('suursoutu-race-v1',JSON.stringify(saved));fresh.run('showSavedRace();resumeRace()');
const restored=plain(fresh.run('snapshot()'));for(const k of Object.keys(saved))if(k!=='chatter')assert.deepEqual(restored[k],saved[k],k);
fresh.run('update(1,performance.now());consume("gel")');assert.equal(fresh.run('raceElapsed'),12601);assert.equal(JSON.parse(fresh.storage.get('suursoutu-race-v1')).inventory.gel,2);
fresh.run('carbs=200;bloodCarbs=20;gutCarbs=25;updateBody(3600,section(),0,false);if(carbs!==200||bloodCarbs!==45)throw Error("Carb absorption");');
assert.equal(run('validRace({...loadRace(),elapsed:NaN})'),false);assert.equal(run('validRace({...loadRace(),inventory:{gel:-1}})'),false);
assert.equal(run('validRace({...loadRace(),rower:"Missing"})'),false);
run('running=true;distance=TOTAL-.0001;speed=10;update(1,performance.now())');assert.equal(storage.has('suursoutu-race-v1'),false);
assert.equal(run("routeRecord('male').name"),'Panu Musakka');
box.localStorage.setItem=()=>{throw Error('blocked')};run('start();pauseRace()');assert(nodes.pauseStatus.textContent.includes('Tallennus ei onnistu'));
run(`running=false;boatSelect.value='4';materialSelect.value='mahogany';selectCrew();`);assert.equal(nodes.materialSelect.value,'');assert(nodes.startButton.disabled);
run(`materialSelect.value='spruce';selectCrew();`);assert.equal(nodes.startButton.disabled,false);
run(`rower=rowers.find(r=>r.name==='Seppo Räty');blisters=0;quality=0;for(let t=0;t<28800;t+=60)updateBody(60,section(),t);if(blisters!==0)throw Error('Seppo blisters');`);
run(`resetBotRacers();const bot=botRacers[0];const requested=criticalStrokePower(bot.rower,bot.freshness)+10;bot.wPrime=100;updateBotWPrime(bot,900,requested);if(bot.wPrime!==0||effectiveBotPower(bot,requested)!==criticalStrokePower(bot.rower,bot.freshness))throw Error('Bot W prime');`);
run(`if(rowerSweatRate(rowers.find(r=>r.name==='Panu Musakka'))<=rowerSweatRate(rowers.find(r=>r.name==='Hanna Tuominen')))throw Error('Sweat profiles');const day=randomRaceDay(rower);if(!Number.isFinite(day.heat)||!Number.isFinite(day.windIntensity)||!Object.hasOwn(RACE_WEATHERS,day.weather)||!['head','cross','tail'].includes(day.windDirection))throw Error('Race-day weather');distance=TOTAL*.7;raceDay={windIntensity:.05,windDirection:'head'};if(section().wind)throw Error('Record calm');raceDay={windIntensity:1,windDirection:'head'};const head=section();raceDay={windIntensity:1,windDirection:'cross'};const cross=section();raceDay={windIntensity:1,windDirection:'tail'};const tail=section();if(!(head.windHead>cross.windCross&&cross.windCross>0&&tail.windHead<0&&Math.abs(tail.windHead)<head.windHead))throw Error('Wind directions');`);
run(`rower=rowers.find(r=>r.name==='Panu Musakka');hydration=energy=100;sodiumBalance=700;cramps=0;wPrime=10;freshness=100;strokePower=110;lastPowerSetting=70;powerSurge=0;updateCramps(60,1,true,{wind:1,speedLoss:.85});const hardCrampGrowth=cramps;cramps=0;wPrime=100;strokePower=60;lastPowerSetting=60;powerSurge=0;updateCramps(60,.4,true,{wind:0,speedLoss:0});if(hardCrampGrowth<=cramps)throw Error('Cramp load');`);
run(`techniqueControl=1;energy=20;hydration=55;wPrime=10;freshness=10;strokePower=110;updateTechniqueControl(3600,{wind:1},1,true);if(techniqueControl>=1)throw Error('Technique fatigue');`);
run(`resetBotRacers();distance=18000;hydration=95;cramps=2;botRacers[0].distance=26000;botRacers[0].hydration=18;botRacers[0].cramps=80;const ambulanceTarget=ambulanceProgress();if(Math.abs(ambulanceTarget-(26000-140)/TOTAL)>1e-9)throw Error('Ambulance risk follow');`);
run(`running=true;previewMode=false;hydration=29;cramps=10;distance=12000;withdrawRace('test',true);if(running||recordEligible||!ui.finish||document.getElementById('finishSummary').textContent.indexOf('Ambulanssivene')<0)throw Error('Medical withdrawal');reset();`);
run(`running=true;for(const [w,h] of [[375,160],[375,300],[900,500]])for(let i=0;i<=100;i++){distance=TOTAL*i/100;const m=mapViewport(w,h),p=pointOnRoute(distance/TOTAL,m.w,m.h);if(Math.abs(p.x+m.x-w/2)>1e-7||Math.abs(p.y+m.y-h/2)>1e-7)throw Error('Camera');}setMapOverview(true);if(mapViewport(375,300).h>300)throw Error('Overview');`);
run(`ferryProgress=.5;const approaching=KIETAVALA_FERRY_STOP_DISTANCE-1;if(ferryLimitedDistance(approaching,approaching+20)!==KIETAVALA_FERRY_STOP_DISTANCE)throw Error('Ferry collision');ferryProgress=0;if(ferryLimitedDistance(approaching,approaching+20)!==approaching+20)throw Error('Ferry dock yielding');`);
console.log('OK: module startup, default menu, first announcement, save/reload, pause, food, finish, invalid storage, material restrictions, immunity, camera.');
